version: '3.1'
services:
  postgres:
    container_name: postgres-container
    image: postgres:12
    volumes:
      - postgres-container:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
